services:
  padel-db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: padel
      POSTGRES_PASSWORD: padel
      POSTGRES_DB: padel