whatsapp:
  prefix: !

spring:
  application:
    name: padel-bot-api
  datasource:
    url: jdbc:postgresql://localhost:5433/padel
    username: padel
    password: padel
  flyway:
    enabled: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect